
######################################

2025-09-28 20:16:00 - Exception occurred:
Traceback (most recent call last):
  File "D:\Projects\roc-bot\conversation.py", line 52, in start
    raise ValueError("This is a simulated ValueError")
ValueError: This is a simulated ValueError

######################################
    
######################################

2025-09-28 20:18:19 - Exception occurred:
Traceback (most recent call last):
  File "D:\Projects\roc-bot\conversation.py", line 52, in start
    raise ValueError("This is a simulated ValueError")
ValueError: This is a simulated ValueError

######################################
    
######################################

2025-09-28 20:31:10 - Exception occurred:
Traceback (most recent call last):
  File "D:\Projects\roc-bot\conversation.py", line 75, in handle_role_selection
    raise ValueError("Huina")
ValueError: Huina

######################################
    